### ISSUE TITLE
linux build

### ISSUE THREAD

**Issue by zjy0** [djm34/ccminer-msvc2015#1]
ubuntu 16.04

lyra2/cuda_lyra2Z_sm5.cuh(805): error: identifier "pTarget" is undefined

lyra2/cuda_lyra2Z.cu(706): error: identifier "lyra2Z_gpu_hash_32_1" is undefined

lyra2/cuda_lyra2Z.cu(708): error: identifier "lyra2Z_gpu_hash_32_2" is undefined

lyra2/cuda_lyra2Z.cu(710): error: identifier "lyra2Z_gpu_hash_32_3" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_00002022_00000000-12_cuda_lyra2Z.compute_50.cpp1.ii".
Makefile:2247: recipe for target 'lyra2/cuda_lyra2Z.o' failed
make[2]: *** [lyra2/cuda_lyra2Z.o] Error 2
make[2]: Leaving directory '/home/home5/zcoin'
Makefile:1793: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/home5/zcoin'
Makefile:583: recipe for target 'all' failed
make: *** [all] Error 2

any requires?

**Comment by djm34** [comment]
this issue has been fixed
