### ISSUE TITLE
Can't install on Ubuntu- no build.sh file

### ISSUE THREAD

**Issue by stonercough** [djm34/ccminer-msvc2015#10]
Hello. I'm trying to install ccminer on ubuntu, and every guide i find on google(and in the INSTALL file) it says the final thing to do is run './build.sh', yet it doesn't exist. Can you help me out and add it back to the repo? Or give me instructions on how to install this without the build.sh file?

**Comment by djm34** [comment]
build.sh was removed because it isn't the proper way to install ccminer on linux here the standard procedure:

./autogen.sh
./configure
make

**Comment by stonercough** [comment]
So I ran make in the directory in terminal, got this error: 

/bin/bash: nvcc: command not found
Makefile:2302: recipe for target 'heavy/heavy.o' failed
make[2]: *** [heavy/heavy.o] Error 127
make[2]: Leaving directory '/home/stonercough/Documents/ccminer'
Makefile:1846: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/stonercough/Documents/ccminer'
Makefile:596: recipe for target 'all' failed
make: *** [all] Error 2


Did I miss a dependency or something?

**Comment by djm34** [comment]
you need to install cuda...

**Comment by stonercough** [comment]
I installed cuda and the nvidia drivers, like this guide says: https://steemit.com/monero/@mobidick/how-to-mine-monero-on-ubuntu-16-04-using-ccminer-cryptonight
It's a different repo, but the same cuda drivers apply right? i also checked the drivers with the commands he suggests and both my cards are showing up.

**Comment by djm34** [comment]
should be ok, I think (although you should probably use a more recent version of cuda, cuda 8 rather than cuda 6.5 however it shouldn't be a problem with this version)

**Comment by stonercough** [comment]
Allright im back. Still haven't gotten ccminer to work. 

I did a fresh install for ccminer, checked cuda was v8.0. theres a softlink /usr/local/cuda --> cuda-8.0 

Deleted the old ccminer i had, re-cloned, ./autogen.sh ./configure make returns this error: https://pastebin.com/3Mnbk9rn

The important error it gives(i think) is `nvcc fatal   : Unsupported gpu architecture 'compute_60'`

After a quick google, i found out this is a problem in cuda 7.5, and every solution online says to download cuda 8. But i'm already sure i installed cuda 8. nvcc -V says v8.0.61 is installed. 

Im using 2 gtx 1070s in case that matters.

**Comment by djm34** [comment]
compute_60 and higher have been introduced in cuda 8, hence the reason why cuda 7.5 would give such error. 
Check that you have on your $PATH the correct version of cuda. 
Might help too if you could remove cuda 7.5 that would probably clear the issue (or at least tell what could be wrong)

**Comment by stonercough** [comment]
Thats the thing- I don't think I ever installed cuda 7.5 on this machine, yet i still get the error. 

$PATH points to a symlink in /usr/local which points to cuda-8.0 in the same dir. 

Could it be a cuda drivers issue? Could i tell it not to use compute_60 and still run the program?

**Comment by djm34** [comment]
you can probably remove the compute_60 line and see if you can compile it. But if it doesn't work (and assuming it is really cuda 8) it is symptomatic of an other problem... 

However, even then, I am not sure you'll be able to get the pascal's working without compute_60 (or compute_61)
