### ISSUE TITLE
GPU #0: invalid device function

### ISSUE THREAD

**Issue by martinambrus** [djm34/ccminer-msvc2015#11]
Hi,

I just tried to do some ZCoin mining today with my Nvidia NVS 4200M (GF119, 10DE-1056, rev. A2) card with all NVidia latest drivers installed. It works with other ccminer forks and the original as well, although with this one I get `invalid device function` errors.

**EDIT:** just tried on Amazon's GRID & Tesla cards and the result is the same

![image](https://user-images.githubusercontent.com/7406402/28208501-40c087a6-688e-11e7-9222-476eb4a81e82.png)

**Comment by djm34** [comment]
what kind of card is this ? What compute/sm version does it use ?
It probably requires to recompile the code with it.

**Comment by martinambrus** [comment]
The card is a laptop NVidia from Dell Latitude e6420. The other ones - GRID & Tesla cards - are fairly high-end desktop ones that you can find in Amazon's AWS instances. If you could provide a step-by-step list of what needs to be done (like, really just bullet points - download this, install that, start the other thing), I can try to recompile this on my Win7 64-bit machine directly.

**EDIT**: just tried to compile this on Ubuntu against the same card and the problem still persists

**Comment by initbar** [comment]
same here..

**Comment by initbar** [comment]
@djm34 nvidia quadro k1000m with fresh compiled binaries but I have the same issue.

**Comment by WannabeKiwi** [comment]
@djm34 I have the same card and issue as martinambrus. It's compute capability 2.1, and I'm guessing that is true also for initbar's k1000m.

I saw in your readme in the source that compute capability below 3.0 has been dropped. So it sounds like you did support CC 2.x at some point. Is this true? If so, is there a version out there that does run on these older cards? (I tried with v0.0.1 but no luck.)

Thanks.

**Comment by djm34** [comment]
It doesn't make much sense to support compute 2.1 for this algo as the performance of a cpu will be much higher. Also in that case the limitation is imposed by cuda 8 which dropped support for compute 2.1
What you could try may-be is to re-compile with cuda 6.5 (for example)
