### ISSUE TITLE
Failed to get extranonce2_size

### ISSUE THREAD

**Issue by jbragg68** [djm34/ccminer-msvc2015#12]
Trying to run zero coin but get

 Failed to get extranonce2_size
[2017-07-15 23:09:59] Stratum subscribe answer id is not correct!
[2017-07-15 23:09:59] JSON-RPC call failed: (unknown reason)
[2017-07-15 23:09:59] ...retry after 30 seconds

**Comment by djm34** [comment]
you need to restart ccminer, that problem happens more or less randomly this is due to a bad connection to the pool

**Comment by jbragg68** [comment]
Do you have any versions that will mine (zer)

Algo: equihash-192,7

https://zero.suprnova.cc

I have one called optiminer-zero but only runs on 8 gig nvidia and I have a
few gtx 1060 6gb rigs.

Thanks
