### ISSUE TITLE
hello, Can you help me ? I need a ccminer compiled with capability 2.1

### ISSUE THREAD

**Issue by realkennyhuang** [djm34/ccminer-msvc2015#13]
I don't know about program. My GPU is old , Geforce GT620M. Ccminer said "invalid device function" , but I know there must be something wrong with compiler and i know it's about compute_xx, Can you help me to compile a old ccminer with capability 2.1 ? thank you very very much.😭

**Comment by realkennyhuang** [comment]
my email is  huang778342106@gmail.com

**Comment by djm34** [comment]
I don't think compute 2.1 is supported in cuda 8. On what coin do you want to run in anyway ? If it is zcoin, you cpu will probably have better performance than really old cards...

**Comment by realkennyhuang** [comment]
thank you
