### ISSUE TITLE
invalid device function

### ISSUE THREAD

**Issue by davezes** [djm34/ccminer-msvc2015#15]
Ubuntu 16.04 Server
Cuda 8.0.61
NVIDIA-SMI 375.66 -- Tesla K80

Everything installed like a charm

Running ./ccminer

yields

[2017-08-11 23:06:20] GPU #0: Tesla K80, 1099.78 MH/s
[2017-08-11 23:06:20] GPU #0: invalid device function
...

Thank you!

**Comment by djm34** [comment]
you probably need to adjust the intensity...

**Comment by davezes** [comment]
Hey djm34.  I've tried varying the intensity without success.  I'll spend some time trying some of the other parameters and check in with results.  Thank you for this project and your help!

**Comment by davezes** [comment]
I got it mining, albeit at a very slow hashrate, by turning on the compute and multiplexer architecture to the earlier 35 (by editing the Makefile).  Is that a reasonable thing to do?  I'll continue to tune the ccminer parameters, as you suggest, to see if I can up the hashrate.
Thanks again, djm34, much appreciated!

**Comment by matu0** [comment]
I've got the same problem. What did you change exactly in your Makefile?

**Comment by djm34** [comment]
you need to chose compute_XX,sm_XX which is relevant to your cards
ie:
compute_61,sm_61 (or compute_52,sm_52) for pascal (available with cuda 8+)
compute_52,sm_52 (or compute_50,sm_50) for Maxwell (cuda 6.5+)
compute_35,sm_35 for 780/780ti/titan (fermi (?))
compute_30,sm_30 for older cards

**Comment by matu0** [comment]
Thanks for the reply, 

how do I choose the compute?
