### ISSUE TITLE
GPU power usage low

### ISSUE THREAD

**Issue by FabianGabor** [djm34/ccminer-msvc2015#18]
GPU power usage low, stuck on 52% with occasional peaks to 75-85% once every 30-60 seconds.

**Gigabyte GTX 1060 6GB**
Power limit 116%
Core 2062 MHz (+167)
Mem 9362 MHz (4681, +880)

For the screen I'm using the Intel onboard graphics, nothing plugged into the GPU.

**Comment by lyolyalya** [comment]
if you are mining zcoin then it's fine.

**Comment by djm34** [comment]
that's the way it is, it is limited by shared memory capacity

**Comment by FabianGabor** [comment]
Ok. Sorry, forgot to mention that it's only when mining Zcoin. 

I wonder if it could be dual mined.

**Comment by Pentadome** [comment]
yea my gpu 0 usage is like 50% but gpu1 is 100%, i dunno why
