### ISSUE TITLE
Stratum connection interrupted

### ISSUE THREAD

**Issue by UselessGuru** [djm34/ccminer-msvc2015#19]
I am seeing many 'Stratum connection interrupted' errors with this miner. This happens on the following pools:
- hashrefinery.com
- zpool.ca

All supported algorithms are affected.

Other miners do not show these symptoms. I can rule out firewall issues, and my network is fast and very stable.

**Comment by djm34** [comment]
the problem originates in tpruvot version... try to play with timing option

**Comment by UselessGuru** [comment]
> try to play with timing option

No success (unless I am missing something)... what timing options in particular?

**Comment by UselessGuru** [comment]
root cause found - I used the following parameters:

" --timeout=3 --statsavg=1 --retries=1 --retry-pause=1"

Removed them -> problem gone!
