### ISSUE TITLE
Merging M7 algo?

### ISSUE THREAD

**Issue by tk-shockwave** [djm34/ccminer-msvc2015#2]
could you merge your M7 algo implementation?

**Comment by djm34** [comment]
I'll look into it next week

**Comment by beilpig** [comment]
Hi I am trying to run this version after compiling on Xubuntu but it continually generates rejects no matter what pool I try running it on. Both Lyra2Rev2 and Lyra2Z do the same. 
![screenshot_2017-02-10_15-01-26](https://cloud.githubusercontent.com/assets/25679055/22814765/d7c1b05a-efa1-11e6-9a50-6ed669558036.png)

Any idea how to resolve this?

**Comment by tk-shockwave** [comment]
read the forum from block 20500 new algo not now.omg

**Comment by beilpig** [comment]
Yeah saw it after I posted this... soz.

**Comment by djm34** [comment]
do you know a pool for M7, so I can test ?

**Comment by tk-shockwave** [comment]
xcn.suprnova.cc still has a XCN pool.
ccminer -a m7 -o stratum+tcp://xcn.suprnova.cc:8008

**Comment by djm34** [comment]
are you aware that suprnova is on the verge of removing xcn ?
(you should probably voice your interest in the coin to ocminer before it happens)

**Comment by pallas1** [comment]
it's been closing for months LoL

**Comment by tk-shockwave** [comment]
Yes it is written for month..maybe it stays.as far as I know poloniex maybe reenable XCN. 
Pallas knows more about it.. 

Here he is..fast than me :-D looks like XCN ist still interesting tho.

**Comment by djm34** [comment]
just asked ocminer on irc: 

djm34: ocminer "This pool is closing soon, please stop mining and withdraw your funds !" is it still the case
ocminer:  dead coin, yes
ocminer: the only one mining it is pallas with an highly optimized miner
ocminer: and he’s the one who’s really interested in it :)

**Comment by tk-shockwave** [comment]
But I would also mine as many others when there would be a up-to-date miner.
Since it came originally from you djm34 I asked if you could port it too.

**Comment by pallas1** [comment]
I'm not the only one mining it, I've got less that 15% of the total hashrate.

**Comment by djm34** [comment]
ok, I have added m7 algo to this release. 
It works, although it may crash on start (and may-require to be restarted several time before it starts mining... (this is under investigation). 
The algo is as it was in the previous version. I haven't tried to merge with the latest version of the algo nor doing any optimization.
