### ISSUE TITLE
build.sh is missing 

### ISSUE THREAD

**Issue by MoinFaraz** [djm34/ccminer-msvc2015#21]
I'm on Ubuntu 16.04 and there's no build.sh inside unzipped archive. The instructions says to ./autogen.sh and ./configure which I did without any issues, but later it ended up with an error when doing ./build.sh 

I've looked into it and found there's no build.sh file under unzipped directory?

`bash: ./build.sh: No such file or directory`

**Comment by djm34** [comment]
Hmm... how did you do build.sh if there isn't any ? :)
I removed build.sh from that release. The correct procedure is, for that release ./autogen.sh ./configure make.

**Comment by MoinFaraz** [comment]
Okay, make ended up with this error: 

![make-error](https://user-images.githubusercontent.com/13995057/31860743-dfac1ed2-b73c-11e7-8369-d74727efa6c1.png)

**Comment by MoinFaraz** [comment]
Okay, make ended up with this error:

![make-error](https://user-images.githubusercontent.com/13995057/31860756-2dd669aa-b73d-11e7-8f2d-0d413dc231f4.png)

**Comment by djm34** [comment]
are you using cuda 9 ?
If yes you should remove scrypt. This one doesn't compile with cuda 9 (or use cuda 8)

**Comment by MoinFaraz** [comment]
Yes, I'm using Cuda 9. Sorry, how do I go about removing scrypt?

**Comment by ghost** [comment]
```
nvcc fatal   : Unsupported gpu architecture 'compute_60'
make[2]: *** [cuda_groestlcoin.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/ccminer-ccminer.Tpo .deps/ccminer-ccminer.Po
mv -f .deps/ccminer-groestlcoin.Tpo .deps/ccminer-groestlcoin.Po
mv -f .deps/ccminer-cuda.Tpo .deps/ccminer-cuda.Po
mv -f .deps/ccminer-myriadgroestl.Tpo .deps/ccminer-myriadgroestl.Po
make[2]: Leaving directory `/root/ccminer'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/ccminer'
make: *** [all] Error 2
```

using [nvidia/cuda:7.5-devel-ubuntu14.04](https://hub.docker.com/r/nvidia/cuda/) as the build environment.

**Comment by djm34** [comment]
you can't compile with compute_60 with cuda 7.5, you need to either use cuda 8 or higher or use compute_52 or 50

**Comment by ghost** [comment]
Using nvidia/cuda:8.0-devel-ubuntu16.04 or removing `nvcc_ARCH += -gencode=arch=compute_60,code=\"sm_60,compute_60\"` worked. How to remove scrypt to compile against nvidia/cuda:9.0-devel-ubuntu16.04?
