### ISSUE TITLE
unresolved externals

### ISSUE THREAD

**Issue by RegencySoftware** [djm34/ccminer-msvc2015#25]
After running the compile I hit the following errors.

LNK2001	unresolved external symbol ___iob_func

LNK1120	1 unresolved externals

Any input would be appreciated.

**Comment by djm34** [comment]
if you could give more info on what you are using...

**Comment by RegencySoftware** [comment]
I have CUDA 8 libraries installed, VS Studio 2015 to compile. I downloaded the main branch and compiled.  At the end of the compile these were the two errors.

**Comment by djm34** [comment]
I never seen this problem, may-be something is missing in your VS Studio install ?
Did you try to compile in Debug mode (the debug version is quite incomplete). If so, switch to Release Win32 or Release x64

**Comment by tamlin-mike** [comment]
@RegencySoftware ___iob_func is for stdio (stdin, stdout, stderr), and should be coming from e.g. msvcrt.lib.
If it's missing for the linker, you are trying to link with mismatched lib.

IIRC older MSVC versions only used ___iob_func for DLL CRT (i.e. MSVCRT), while I believe the later versions always use it. Also, make sure you target the correct OS and with the correct toolchain (incl. headers and libs).

For additional info, turn on VERBOSE for the linker.

++luck;
