### ISSUE TITLE
GPU #0: an illegal memory access was encountered

### ISSUE THREAD

**Issue by lukiifaz** [djm34/ccminer-msvc2015#26]
Bin\Lyra2z-NVIDIA\ccminer_cuda9.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u xxxx.xxxx -p x
Sys: Win 10
CPU: i7-7700
RAM 16GB
GPU: GTX 1060 6GB
Drivers: v388.31 15-11-2017
During the problem, the value of 12GH / s, normally 1142.52 kH / s. Multipoolminer did not detect the problem.

**Comment by djm34** [comment]
it looks like a driver crash. 
May-be it is due to a too high intensity (?). This is what usually trigger those illegal memory access.
The illegal memory access was related to the kernel or something else ?

**Comment by nsummy** [comment]
Did you overclock the card?  Usually that is the culprit.

**Comment by UselessGuru** [comment]
The Lyra2z algeorithm is especially heavy on memory handling and therefore more prone to crashes caused by overclock (just my experience - most other algos work fine with higher mem overclock - Lyra2z crashes).
-> Lower your memory overclock!

**Comment by tconrado** [comment]
@lukiifaz did you solve the issue? I have the same problem...

**Comment by tconrado** [comment]
@djm34, thanks for sharing! I just lowered the intensity and the error did not happen anymore
