### ISSUE TITLE
Trojan alert ?!

### ISSUE THREAD

**Issue by wuyi1983** [djm34/ccminer-msvc2015#27]
Hi , if i extract the ccminer_cuda9.exe archive I got a trojan alert ?

win32/virus.risktool.46f

So what's going in here please?

Cheers

**Comment by djm34** [comment]
nothing... false positive. Most miner got one of those...

ps: these exe are brought here as a courtesy... the proper way to use the content of github is to compile yourself

ps2: if I had introduced a virus in my release, I would probably not tell that I did it... :-)
 So if you don't trust the exe (nor the dev) don't use it.

**Comment by wuyi1983** [comment]
Of course we trust you.

Just in case the released exe file was hacked.

Thanks.
