### ISSUE TITLE
error message on start up

### ISSUE THREAD

**Issue by betiteh0777** [djm34/ccminer-msvc2015#29]
Hi when I try to start the miner error message appear: ccminer_cuda9.exe - System Error  The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem. 

I have reinstalled but it didn't help. It does the same error with the other miner too.....

**Comment by gsgorveatt** [comment]
https://www.microsoft.com/en-gb/download/details.aspx?id=40784
will fix it

**Comment by gsgorveatt** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145
sorry this is for vcruntime140

**Comment by djm34** [comment]
yes you need msvc 2015 runtime dll (although it should be a static build)

**Comment by betiteh0777** [comment]
yeah thanks! have installed it and miners works now.......
