### ISSUE TITLE
 Unknown algo parameter 'lyra2Z'

### ISSUE THREAD

**Issue by ceozero** [djm34/ccminer-msvc2015#3]
![image](https://cloud.githubusercontent.com/assets/22513657/22830794/c6f3aab2-efe2-11e6-8a65-0009585be8f9.png)

**Comment by djm34** [comment]
this isn't the version I wrote, looks like you are running on some old version of ccminer (1.7.6)

**Comment by djm34** [comment]
yeah... apparently I updated a version from another directory which indeed doesn't include the lyra2Z algo... 
ok I have uploaded the correct one this one.
