### ISSUE TITLE
Please add Maxwell GPU support (gtx 970, 980, etc) for lyra2z

### ISSUE THREAD

**Issue by kubotaguy** [djm34/ccminer-msvc2015#30]
Hi, 
I have the following graphics card https://www.techpowerup.com/gpudb/b3211/evga-gtx-980-classified-kingpin-acx-2-0

The new CUDA 9 compile produces the error: " GPU #0: no kernel image is available for execution on the device"  when I try to run the lyra2z algorithm

**Comment by Fever905** [comment]
Also not working with Tesla K80.  

With CUDA 9 I also have issues with the compute_20

**Comment by djm34** [comment]
compute_20 is obsolete since cuda 8.5
A new release is coming and should address these problems

**Comment by djm34** [comment]
the binaries compiled with cuda 9 didn't include support for older card (by mistake) however a new release is coming
