### ISSUE TITLE
GPU #0: no kernal image is available for execution on device

### ISSUE THREAD

**Issue by nexus1952** [djm34/ccminer-msvc2015#31]
![lyra2z](https://user-images.githubusercontent.com/34809040/34325756-4fe46460-e8c1-11e7-9b57-73695760f681.jpg)

**Comment by mkorobeynikov** [comment]
Same problem with MSI GTX 960

**Comment by kubotaguy** [comment]
I believe this is directly related to Issue #30. The Maxwell GPUs were not included in the latest build. They are fully capable of running Cuda 9 they just need to have the right variables added

**Comment by djm34** [comment]
new release (with source ) is coming and will include this fix.
