### ISSUE TITLE
1070 ti Core too high ?

### ISSUE THREAD

**Issue by cloudwalker2020** [djm34/ccminer-msvc2015#32]
I have my 1070 ti set to + 200core/ 700 mem at 65% TDP. On EWBF equihash my core is around 1650mhz average. When I run lyra2z ccminer, the core jumps over 2000, I don't let it run because I don't think it should be that high? Any idea?

**Comment by lyolyalya** [comment]
it's fine cause lyra2z has a low GPU load(40%)----->low temperatures----->higher boost
