### ISSUE TITLE
lyra2h miner "result does not validate on CPU"

### ISSUE THREAD

**Issue by lyolyalya** [djm34/ccminer-msvc2015#33]
hello.what port i need to use for GPU mining?just "result does not validate on cpu" with all cpu ports described on the pool.

ccminer -a lyra2h -o stratum+tcp://pool.hppcoin.com:"any port" -u lyolyalya.1 -p x

**Comment by djm34** [comment]
what card are you using ?
also for the moment it is better to use sgminer which is a tad faster

**Comment by lyolyalya** [comment]
GTX 1070, win 10(1703) latest drivers.all other algos and coins are fine.
don't use sgminer.if there is no big deal that it's fine with lower hashrate.

**Comment by djm34** [comment]
tested the miner on a 1080ti, 1070, 980 and 1050 everything was ok (on jkpool however). 
Use intensity of 14 (I think it should still work with intensity of 16, but without extra benefit)

**Comment by lyolyalya** [comment]
nope.was trying with -i 11.same thing.which port are you using?

**Comment by djm34** [comment]
I used jkpool

**Comment by lyolyalya** [comment]
http://img.techpowerup.org/171231/p1kalmig2k624.jpg
http://img.techpowerup.org/171231/zp5tm1qbi6.jpg

**Comment by lyolyalya** [comment]
seems like you post wrong miner...it's 0.0.2 in the console

**Comment by djm34** [comment]
yep just verified, there is something wrong here

**Comment by djm34** [comment]
release updated (and bug corrected) use the new file ccminer.rar
(but again you should probably use sgminer-msvc2015 with your nvidia card as it is a tad faster than ccminer)

**Comment by lyolyalya** [comment]
will try.what hasrate i can count from 1070?

**Comment by djm34** [comment]
70-80kh/s on sgminer against 50-60 on ccminer

**Comment by lyolyalya** [comment]
not so prifitable...=)thanks
