### ISSUE TITLE
cuda gencode for Tesla K80 Zcoin

### ISSUE THREAD

**Issue by myjupiter** [djm34/ccminer-msvc2015#38]
Hello
trying to run ccminer for Zcoin and still stuck on GPU #0: invalid device function
please advice config for Tesla K80
NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
`nvcc_ARCH = -gencode=arch=compute_30,code=\"sm_30,compute_30\"`
also try 35,37 but have no luck

`ccminer -V`
*** ccminer 0.0.2-djm34 for nVidia GPUs by djm34 ***
    Built with the nVidia CUDA Toolkit 8.0

  Originally based on Christian Buchner and Christian H. project based on tpruvot 1.8.4 release
  Include algos from alexis78, djm34, sp, tsiv and klausT.
  *** News (28/12/2017): lyra2h algo for HPP coin 

BTC donation address: 1NENYmxwZGHsKFmyjTc5WferTn5VTFb7Ze (djm34)
ZCoin donation address: aChWVb8CpgajadpLmiwDZvZaKizQgHxfh5 (djm34)

ccminer v0.0.2-djm34
libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

`uname -a`
Linux ubuntu14 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

`nvcc -V`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

`gcc --version`
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

`nvidia-smi`
Tue Feb 27 03:26:41 2018       
+--------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |

Thank you.

**Comment by djm34** [comment]
the config should be 35 or 37 (technically 37 is for the Tesla but 35 works as well)
The K80 code was tested long ago on ubuntu 16.04 and was working. 
Invalid device means your card isn't recognize. 
Does nvidia-smi see your card ?
Nvidia-smi should display every card which are on the system, if not you should reinstall the drivers.
