### ISSUE TITLE
Segmentation Fault when running on AWS with NVidia K80 (compute 3.7) instances

### ISSUE THREAD

**Issue by beilpig** [djm34/ccminer-msvc2015#4]
Have tried installing and running (several times) on AWS P2.8xLarge instances running Ubuntu 16.04 but generates a segmentation fault after initialisation...

![capture](https://cloud.githubusercontent.com/assets/25679055/22866916/5a9f59f4-f1c9-11e6-8bf7-905fe34045fa.PNG)

**Comment by beilpig** [comment]
Tried cloning from the source directory and building as per instructions (using Cuda 8.0 though) and this executes but generates Invalid Device Function errors...

![capture](https://cloud.githubusercontent.com/assets/25679055/22867080/2d28dc4a-f1cc-11e6-8d03-ffba9a3fea6d.PNG)

**Comment by djm34** [comment]
Is this the latest source (not from the release but from the master) ?
did you compile with compute_35,sm_35 and nothing else. cuda 8 should be fine.
Also check if you get the same problem on instance with only one k80 (in principle ccminer can handle up to 16 gpu but we never know)

ps: apparently it isn't the latest, the latest should display a different version number on linux

**Comment by beilpig** [comment]
I did a git from https://github.com/djm34/ccminer-msvc2015.git 
and just specified ./configure --with-cuda=/usr/local/cuda-8.0 then make

**Comment by beilpig** [comment]
How does one compile with just compute_37?

**Comment by beilpig** [comment]
Is there a quick way to compile for just one algorithm? It takes a long time to compile all this extraneous stuff that is irrelevant to lyra2Z. Would be helpful if configure could take a parameter to create the minimal make file for a given algo! Just saying <would be nice>... Also, this code does not compile on Visual Studio 2015 x64. Generates a tonne of errors.

**Comment by beilpig** [comment]
OK I managed to get this working on the AWS instance as described above. I edited the makefile to use only compute_35 (compute_37 seems to generate compile errors with some of the algorithms like Heavy)

**Comment by beilpig** [comment]
Have now tested this on both the p2.8xLarge and p2.16xLarge... the latter spat the dummy with a memory corruption error, but after restarting ran with no issue!?!? wierd... can get about 1485kH/s on the 16 rig and 762 on the 8 rig... bit sad as each device is only achieving about 92kH/s each... My Quadro M2000 gets 328kH/s!

**Comment by djm34** [comment]
yes currently, in the way the lyra code was arranged, it couldn't use compute_37. I am currently restructuring the whole lyra2Z getting rid of many useless conditions used in the code so it will be easier to read/test and it should be also able to compile compute 3.7 

regarding your question about compiling only one algo... no I am afraid it isn't possible to compile only one algo (it would require a full rewrite of ccminer core, and this is out of scope for the moment...)

regarding compilation on x64, I tested a day ago and it seems fine (compiled, run and found shares)
please open a new ticket if the problem remains (again you need to use the latest release, the first one had a few bugs left in the global setting coming from the porting to msvc2015)
