### ISSUE TITLE
Create a ccminer with scryptn2 in it

### ISSUE THREAD

**Issue by platinum4** [djm34/ccminer-msvc2015#41]
@djm34 I didn't know how else to find you, do you think this is possible?

**Comment by djm34** [comment]
I don't know what is scryptn2

**Comment by platinum4** [comment]
https://miningpoolstats.stream/bitcoinsubsidium
Uses Scrypt-N or "scryptn2" when mined on CPU miners like cpuminer-opt-3.19.0 or srbminer-cpu-0.8.2

https://github.com/doktor83/SRBMiner-Multi/releases/tag/0.5.6
https://github.com/JayDDee/cpuminer-opt/releases/tag/v3.18.0

Can you check these out and see if it's possible man?  You're a God in this gpuminer compiling space.

**Comment by djm34** [comment]
Sorry I don't have time and am under contractual obligation to not release miners. (also I never released public miner for individuals as it usually doesn't cover dev. cost)

**Comment by platinum4** [comment]
Understood, can you answer the question of whether it is possible to do on this algo or not please?  Y/N

**Comment by djm34** [comment]
hmm.... scrypt-N (assuming it is the same, don't have time to do extensive research outside of my memory :D ) has already been coded for GPU (vertcoin was using script-N back in 2014).

**Comment by platinum4** [comment]
Yeah I mined EXEcoin and Vertcoin on lasybear's cgminer rewraps back in 2014, I've been here since you have that's why I knew to ask the Master.

That's scrypt:2048 which is not the same quite as scrypt:1048576

I think it can be done but the coin devs say would not be worth it.  Problem is I can only find old ass cudaminers or cgminer for any scrypt-n/scrypt-jane which don't work on 30-series.

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/142166721-a37bdb19-0040-480f-b7a8-7613e1d6eaef.png)

**Comment by platinum4** [comment]
Think that was when we were squeezing an extra 1Mh/s out of 290Xs back in that summer of 2014 when X13 hit then X15 came out in July

**Comment by platinum4** [comment]
aznboi84 I remember that guy: x15

**Comment by platinum4** [comment]
Contractual obligations do not allow djm34 to work on or release miners to public.

**Comment by djm34** [comment]
well I never worked on public release for free in any way :D

**Comment by platinum4** [comment]
Nope you were paid by nicehash, not a mystery there.  I'll find @OhGodAPet on Discord somewhere, been a year or two since I have messaged Wolf...

**Comment by djm34** [comment]
ah didn't know I was paid by Nicehash at that time :D. Wolf isn't cheap either good luck

**Comment by platinum4** [comment]
Hell no he's not last time I had a scrypt-chacha kernel from him it was 1 BTC but I was selling it for that as well so ;D

Good to talk to you man unfortunate you can't help out here but I'm sure you're rich so take care buddy.

If you weren't paid by Nicehash back then, sorry I was wrong in that assumption.
