### ISSUE TITLE
pools are reporting poor hashrates.

### ISSUE THREAD

**Issue by lyolyalya** [djm34/ccminer-msvc2015#6]
hey.using your miner.it gives me 4100 KH with 3x1070.but miningpoolhub and suprnova tells me only 2700 KH max.i wrote to miningpoolhubs forum.he tell me there is a bug in ccminer.can you look at this issue closer?

**Comment by djm34** [comment]
did he happen to tell you what was the bug ?
After how many time ? (technically what is reported by the pool is only an average based on the number of shares the miner solved and difficulty)

**Comment by lyolyalya** [comment]
i was mining about 7 hours on miningpoolhub and suprnova.in graphs section it was only 3000 KH max.

that's what he said.
"What miner are you using?
I heard that ccminer has problem with hashrate. ccminer Dev is finding bug currently."

**Comment by djm34** [comment]
I am the ccminer dev... and I don't find bugs...

**Comment by lyolyalya** [comment]
i know=)that's why i wrote to you=)so...you think that 2.7 Mh of pools speed instead of 4.1 Mh of miners speed is okay?i see, that zxc is very "slow" coin now and i was thinking about average reports, not max...but other coin are fine...well...just asking for sure.thanks.

**Comment by djm34** [comment]
which port are you using on suprnova ?

**Comment by lyolyalya** [comment]
1596. you think should try 1598?

**Comment by djm34** [comment]
GPU-Ports: 1596, 1569 (high diff)
CPU/GPU-Ports: 1598 (low diff)
CPU-Port-Super-Low-Diff: 1599 (very, very slow CPU's)

yes you should rather use the "low diff"

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/23339564/390967b6-fc2e-11e6-99ab-0a8fa409565a.png)

**Comment by djm34** [comment]
lol, yeah I didn't pay attention to the first one. 
Try using the low diff (I have around 3MH/s) and I don't see lots of shares. 
If the share number is too small, the pool can't calculate properly the hashrate

**Comment by djm34** [comment]
actually the pool report 4.7MH/s while I have only 3MH/s
(honestly I think the problem is more on pool side)

**Comment by lyolyalya** [comment]
will try low diff port.thanks.

**Comment by lyolyalya** [comment]
yepp.low diff port gives me my 4100 KHs.sorry for trouble.will ask miningpoolhub for low diff ports.thanks again.
p.s.hope any speedups soon=)cause only 40% of using gpu is so...strange=)

**Comment by djm34** [comment]
ok, in the mean time I commited a small change which may improve the hashrate displayed by the pool (not entirely if it will be better).

**Comment by lyolyalya** [comment]
understood.well...hope never dies=)

**Comment by lyolyalya** [comment]
hey.want to ask.if miningpoolhub reports me 2600-2800 Kh and miner 4100 Kh - which hashrate i need to use on WTM to calculate earnings?

**Comment by djm34** [comment]
go to an another pool (may-be getting robbed...)

**Comment by lyolyalya** [comment]
the question is not about a pool actually=)but i get it...

**Comment by djm34** [comment]
technically you should use the miner hashrate...

**Comment by lyolyalya** [comment]
yes=)but have some doubts, you know=)tried suprnova yesterday - have problems with connection time after time...and theirs high diff port really very high.1-2 share per minute in the best case...low diff gives less earnings as far as i can see...but probably you are right.will change the pool to suprnova today and will give a try to it...

**Comment by djm34** [comment]
actually what you can try is to run on both pool for a day and see how it compares to whattomine estimation (I can have an another look, could be due to some latencies in sending shares/receiving new work. aside from that I don't know and fool play is always an option in crypto...)

**Comment by lyolyalya** [comment]
trying suprnova now...you know...even with 1-2 shares per minute on high diffport pool reports 4800 kh\s last hour...

**Comment by djm34** [comment]
so it is working fine on supernova (?)

**Comment by lyolyalya** [comment]
looks like...tomorrow give you final result if you interesting.

**Comment by djm34** [comment]
sure

**Comment by lyolyalya** [comment]
yepp...suprnova - much better.on MPH i earn 0.7 xzc per day.with suprnova - 0.6 xzc for 8 hours=)but can't reach 2-2.5 like WTM says.but even now - 4$ from one 1070 with 80 W - the best choice i guess=)
suprnova gives slightly more rejects - 0.7%...aand they have very strange dashbord(mona especially=) that veeery slow...but when i see my balances - it's fine.
so.here it is - thanks for the help.
P.S. and yes - even high diff port reports my hashrate correctly.i have 4800 Kh/s now.suprnova tells me up to 8000 kh/s time after time.
P.P.S.suprnova lagging now...=(many reject and disconnecting...rrr
![image](https://cloud.githubusercontent.com/assets/16507768/23990142/c4659754-0a3d-11e7-99a6-0c8c73154172.png)

**Comment by lyolyalya** [comment]
annd with this lags have not such promising results...only 1 xzc for 16 hours...so 2 xzc per day is unreachable for me any way...need to try pool.mn...

**Comment by lyolyalya** [comment]
what's wrong with this xzc...pool.mn hardly reaches 4600kh\s...

**Comment by djm34** [comment]
difficult to say may-be you should report your findings to pool owners

**Comment by lyolyalya** [comment]
done long ago.MPH seems working well last 12 hours.0.7 xzc for 8 hours and pool hasrate rised up from 3200 Mh to 6000. suprnova from 4700 to 2000.so miners really migrate from suprnova to MPH...but price of xzc is falling down so...will see...
