### ISSUE TITLE
GPU #0: invalid device function

### ISSUE THREAD

**Issue by sides580** [djm34/ccminer-msvc2015#7]
I got a GTX 770. Seems to be just trying to set the GPU frequency and keeps getting.
GPU #0: invalid device function

Any tips on how to fix this? Just keeps trying random frequencies it seems. Very strange. I'll try to look at code. I'll have to find the right compiler.

**Comment by djm34** [comment]
ccminer exe probably needs to be recompiled with the compute version of your card 
either compute_30,sm_30 or compute_35,sm_35 (probably 30, don't remember for sure for that card)
(it has nothing to do with clock settings)

**Comment by ghost** [comment]
I want IP Please.
-o http://13.76.210.1:18888   =   Failed T-T

**Comment by djm34** [comment]
@UdonSL I am afraid your question goes beyond the scope of this issue (and on any issue related to the code for that matter). The address  (and port) you have to enter is either the address and the port of a pool or the (local) address (hence yours) in case of mining on a local wallet. 

Please checks forums (such as bitcointalk) for general tutorial regarding using miners and mining on wallet/pool

**Comment by ghost** [comment]
I experimented with another machine. I did not find the problem I encountered anymore.
I think maybe my video card does not support it.
How do I know if my machine can run your program?

**Comment by djm34** [comment]
well you don't say anything about the card you use...
This program is for nvidia card only, for amd card you need to use sgminer. 
However as I stated in my previous message you should gain a little experience about mining and find info on the relevant forums.

**Comment by ghost** [comment]
I do not understand this much.
I just started studying recently.
I have solved the code, try it wrong for a while. I understand enough.

Okay, now I want to ask you something else. My notebook uses a nVidia GeForce 820M
When running the program. It appears that the GPU # 0: invalid device function
Does this mean that my card is not working?

**Comment by djm34** [comment]
use the latest release, this should now support compute_30 cards (at least will work for the gtx770) not entirely sure what is the 820M (not familiar with laptop cards)

**Comment by ghost** [comment]
Thank you very much for your help😊

On Jun 3, 2017 11:49 PM, "djm34" <notifications@github.com> wrote:

use the latest release, this should now support compute_30 cards (at least
will work for the gtx770) not entirely sure what is the 820M (not familiar
with laptop cards)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/djm34/ccminer-msvc2015/issues/7#issuecomment-305986970>,
or mute the thread
