### ISSUE TITLE
the application was unable to start correctly (0xc00007b)

### ISSUE THREAD

**Issue by dragonvenom500** [djm34/ccminer-msvc2015#8]
Are there any dependencies standard windows 10 does not meet to run the program? I install all kinds of runtimes, and no matter what I do, I get this error. I'm trying to run the program normally, trying to mine zcoin.

**Comment by djm34** [comment]
it is a static build and it doesn't require any dependency.

Which version are you using and which card do you use ?
Also when you say "run the program normally" what do you use ?

**Comment by dragonvenom500** [comment]
It is ccminer  v0.0.3. The card I am using is a nvdia gtx 1060. I am running the program with a .bat file that has the exact same script as found on the zcoin website. For the program to actually run, will I need need to have set up a wallet and joined a pool before it will start?

**Comment by djm34** [comment]
works perfectly fine on both my 1070 and 080ti on windows 10 pro...
what is in your bat file ?
you most likely need to register to a pool (or download a wallet) to run on it, however it shouldn't return that sort of message but just exit if you didn't provide any pool address or wallet address

**Comment by Micdvd85** [comment]
@dragonvenom500 I get the exact same error on windows10, just trying to run a simple .bat file it won't do anything except give me the error. I also got the runtime error as well but eventually fixed that on my own. However I cannot get past this error...

**Comment by Micdvd85** [comment]
@djm34 it's not a pool error or anything else... it's a windows error that closes the program instantly.

**Comment by Micdvd85** [comment]
@dragonvenom500 I finally got mine to work. I had to install the Microsoft Visual C++ 2015 x86 version. If you only have the 64bit version it won't work. Make sure you have both and see if that solves your problem.

**Comment by ipsumium** [comment]
@Micdvd85 Thank you, I've been debugging for three hours. x86 version solved vcruntime140.dll error in my case
