### ISSUE TITLE
getting "Unable to query number of CUDA devices! Is an nVidia driver installed?"

### ISSUE THREAD

**Issue by wulfboy-95** [djm34/ccminer-msvc2015#9]
Current driver version is 342.01

**Comment by djm34** [comment]
well the problem is on your side... need more details such as which systems you run on... etc...
(that sort of problem appears when your drivers aren't correctly installed on linux)

**Comment by ghost** [comment]
I'm having this same issue. Running ccminer on arch linux. My driver is xf86-video-nouveau (https://wiki.archlinux.org/index.php/Nouveau). My device drivers:

> lspci -k | grep -A 2 -E "(VGA|3D)"
> 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
>         Subsystem: Dell Device 06ae
>         Kernel driver in use: i915
> 08:00.0 3D controller: NVIDIA Corporation GK208M [GeForce 920M] (rev a1)
>         Subsystem: Dell Device 06ae
>         Kernel driver in use: nouveau

Cuda version: 8.0.61-2

**Comment by djm34** [comment]
you need to install nvidia driver from nvidia
